cloud: /subscriptions/68e5d74d-cc6b-4be6-9606-cd1c77fa55f0/resourcegroups/vibhansa-ray-aks-rg/providers/anyscale.platform/clouds/tanyaanyscalecloud
worker_nodes:
  - instance_type: "2CPU-8GB"
    min_nodes: 0
    max_nodes: 10
max_resources:
  CPU: 80
