global:
  cloudDeploymentId: cldrsrc_4zvnxbesvhey3wj296lgcfqfwl
  cloudProvider: azure
  controlPlaneURL: https://console.anyscale.com
  auth:
    iamIdentity: "cabfa12d-7cfe-4db7-895e-e90bae86f3ed"        # Managed identity client ID for operator workload identity
    anyscaleCliToken: "aph0_CkcwRQIhAMCvU0YlPdjc_U2wMg6EJt187b3rkWe1AJfVj7_N06-_AiADmBAaVUodc8gxO9lcNUB8xMWkRaCEBt3N4PbJV4f3fhJhEiBeIulwGSIcyM5_aNxYT_uEgA54N4KpG3EQG1sdiQbzIhgBIh51c3JfajdzZTk5ZW05eDUxc24ycW0ybmtzZTgzczM6CwjR1MnNBhDIkqVsQgsIpduwzAYQyJKlbPIBAA"
  azure:
    clientId: "cabfa12d-7cfe-4db7-895e-e90bae86f3ed"           # Client ID for MSI used by operator

ingress-nginx:
  enabled: true
  controller:
    admissionWebhooks:
      enabled: false
    service:
      type: LoadBalancer













