global:
  cloudDeploymentId: 
  cloudProvider: azure
  controlPlaneURL: https://console.anyscale.com
  auth:
    iamIdentity: ""        # Managed identity client ID for operator workload identity
    anyscaleCliToken: ""
  azure:
    clientId: ""           # Client ID for MSI used by operator

ingress-nginx:
  enabled: true
  controller:
    admissionWebhooks:
      enabled: false
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"

















