global:
  cloudDeploymentId: cldrsrc_4zvnxbesvhey3wj296lgcfqfwl
  cloudProvider: azure
  controlPlaneURL: https://console.anyscale.com
  auth:
    iamIdentity: """
    anyscaleCliToken: ""
  azure:
    clientId: ""           # Client ID for MSI used by operator

ingress-nginx:
  enabled: true
  controller:
    admissionWebhooks:
      enabled: false
    service:
      type: LoadBalancer













