global: 

  auth: 

    anyscaleCliToken: <your-anyscale-cli-token>

  cloudDeploymentId: cldrsrc_kbkiwr8djfbykdn1s8pqsg5m6u 

  cloudProvider: azure 

  controlPlaneURL: https://console.azure.anyscale.com 

  storage:
    azure:
      accountName: anyscalestorageacount
      accountKey: <your-storage-account-key>

workloads: 

  serviceAccount: 

    name: anyscale-operator 

  instanceTypes:
    enableDefaults: true
    additional:
      head-d48:
        resources:
          CPU: 20
          memory: 80Gi
      worker-d48:
        resources:
          CPU: 46
          memory: 180Gi

 

### Optional: install the ingress-nginx controller as a sub-chart 

ingress-nginx: 

  enabled: true 

  controller: 

    service: 

      annotations: 

        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz" 