# ========== PERSISTENT VOLUME CLAIM (AZURE BLOB STORAGE) ==========
# This PVC provides access to Azure Blob Storage via Blobfuse2 CSI driver.
# It mounts the container specified in the StorageClass configuration.
#
# Key features:
#   - Read-write many access (multiple pods can mount simultaneously)
#   - Blobfuse2 CSI driver for efficient blob storage mounting
#   - Large capacity for dataset distribution (5TB requested)
#   - Used by both Ray head and worker pods
#
# Related resources:
#   - StorageClass: storageclass-blobfuse2.yaml
#   - Consumer: rayjob-gpu.yaml, rayjob-cpu.yaml

apiVersion: v1
kind: PersistentVolumeClaim

# ========== METADATA ==========

metadata:
  name: blob-pvc

# ========== SPECIFICATION ==========

spec:
  # Access mode: multiple pods can read and write simultaneously
  # This is essential for distributed Ray jobs accessing the same dataset
  accessModes: [ "ReadWriteMany" ]
  
  # StorageClass that defines the Azure Blob Storage backend
  storageClassName: azureblob-fuse2
  
  # Storage capacity requested
  # Note: This is the requested capacity; actual quota depends on storage account limits
  resources:
    requests:
      storage: 5Ti  # 5 Terabytes for AG News dataset and model artifacts
