apiVersion: storage.k8s.io/v1 
kind: StorageClass

metadata:
  name: azureblob-fuse2

provisioner: blob.csi.azure.com
parameters:
  protocol: fuse
  storageAccount: __STORAGE_ACCOUNT__
  containername: __CONTAINER__
  resourceGroup: __RESOURCE_GROUP__
  mountWithWorkloadIdentityToken: "true"

mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --tmp-path=/mnt/blobfusecache

allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate

